Upgrade to CentOS 9
Includes postgres upgrade logic from 12 to 13

diff --git a/assets/init/postgres-init b/assets/init/postgres-init
--- a/assets/init/postgres-init
+++ b/assets/init/postgres-init
@@ -13,16 +13,21 @@ export C035="\e[35m"
 export C036="\e[36m"
 export C037="\e[37m"
 
-PGVERSION=$(postgres --version | egrep -o "[0-9]{1,}\.[0-9]{1,}")
+PGVERSION=$(postgres --version | egrep -o "1[0-9]")
 PGHOME="/var/lib/pgsql"
 PGDATA="${PGHOME}/data"
+PGDATA_OLD="${PGHOME}/data_old"
+PGDATA_OLD_RENAMED="${PGHOME}/data_old.$(date --rfc-3339=seconds)"
 
 if [ -d "${PGDATA}/base" -a -f "${PGDATA}/PG_VERSION" ]; then
   PGDATA_VERSION=$(cat "${PGDATA}/PG_VERSION")
-  if [ "${PGDATA_VERSION}" = "${PGVERSION}" ]; then
-
-    echo -e "${PREFIX} ${RED}${PGDATA} exists but needs upgrade ${PGDATA_VERSION} != ${PGVERSION}${ENDCOLOR}"
-    exit 200
+  if [ "${PGDATA_VERSION}" != "${PGVERSION}" ]; then
+    echo -e "${PREFIX} ${ORANGE} Postgresql database exists but will be upgraded from ${PGDATA_VERSION} to ${PGVERSION}${ENDCOLOR}"
+    if [ -d ${PG_DATA_OLD} ]; then
+      echo -e "${PREFIX} ${ORANGE} Renaming ${PGDATA_OLD} ${PGDATA_OLD} to ${PGDATA_OLD_RENAMED}${ENDCOLOR}"
+      mv ${PGDATA_OLD} "${PGDATA_OLD_RENAMED}"
+    fi
+    su postgres -c "PGSETUP_INITDB_OPTIONS=\"-E UTF8 --auth=trust\" postgresql-upgrade ${PGDATA}" || { echo -e "${PREFIX} ${RED} Failed to upgrade the postgresql database${ENDCOLOR}" ; exit 1; }
   fi
 else
   echo -e "${PREFIX} ${GREEN}initdb -E UTF8 --pgdata ${PGDATA}${ENDCOLOR}"
