Publish images on github

diff --git a/.github/workflows/publish_images.yaml b/.github/workflows/publish_images.yaml
--- a/.github/workflows/publish_images.yaml
+++ b/.github/workflows/publish_images.yaml
@@ -1,4 +1,4 @@
-name: Build and publish OCI Images
+name: Publish OCI Images
 
 on:
   push:
@@ -8,28 +8,18 @@ on:
     # * is a special character in YAML so you have to quote this string
     - cron: '0 1 * * *'
   workflow_dispatch:
-    inputs:
-      pulpcore:
-        description: 'Release branch (e.g. 3.7)'
-        required: true
 
 jobs:
-  build:
+  publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.inputs.pulpcore }}
       - name: Download s6-overlay
         run: |
           wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
       - name: Set version
         run: |
-          if [ -n "${{ github.event.inputs.pulpcore }}" ]; then
-            version="${{ github.event.inputs.pulpcore }}"
-          else
-            version="${GITHUB_REF#refs/heads/}"
-          fi
+          version="${GITHUB_REF#refs/heads/}"
           echo "Building and publishing $version."
           echo "VERSION=$version" >> $GITHUB_ENV
       - name: Build the images
@@ -41,6 +31,8 @@ jobs:
             docker build --file pulp_nightly/Containerfile --tag pulp/pulp:nightly . || true
           fi
           docker build --file pulp/Containerfile --tag pulp/pulp:$VERSION .
+      - name: Test the images
+        run: assets/test.sh "pulp/pulp:$VERSION"
       - name: Docker login
         env:
           DOCKER_BOT_PASSWORD: ${{ secrets.DOCKER_BOT_PASSWORD }}
@@ -48,10 +40,55 @@ jobs:
         run: echo "$DOCKER_BOT_PASSWORD" | docker login -u "$DOCKER_BOT_USERNAME" --password-stdin docker.io
       - name: Push ci image to dockerhub
         run: |
+          docker push docker.io/pulp/pulp:$VERSION
           if [ "$VERSION" = "latest" ]; then
             docker push docker.io/pulp/pulp-ci-centos:latest
             docker push docker.io/pulp/pulp-galaxy-ng:latest
-            # Be resilient if this fails
-            docker push docker.io/pulp/pulp:nightly || true
+            # Let this be the last thing so it can indicate failure without breaking anything else
+            docker push docker.io/pulp/pulp:nightly
           fi
-          docker push docker.io/pulp/pulp:$VERSION
+      - name: Display log on error
+        if: failure()
+        run: docker logs pulp
+
+  ghcr:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Download s6-overlay
+        run: |
+          wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
+      - name: Set version
+        run: |
+          version="${GITHUB_REF#refs/heads/}"
+          echo "Building and publishing $version."
+          echo "VERSION=$version" >> $GITHUB_ENV
+      - name: Build the images
+        run: |
+          if [ "$VERSION" = "latest" ]; then
+            docker build --file pulp_ci_centos/Containerfile --tag pulp/pulp-ci-centos:latest .
+            docker tag pulp/pulp-ci-centos:latest ghcr.io/pulp/pulp-ci-centos:latest
+            docker build --file pulp_galaxy_ng/Containerfile --tag ghcr.io/pulp/pulp-galaxy-ng:latest .
+            # Be resilient if this fails
+            docker build --file pulp_nightly/Containerfile --tag ghcr.io/pulp/pulp:nightly . || true
+          fi
+          docker build --file pulp/Containerfile --tag ghcr.io/pulp/pulp:$VERSION .
+      - name: Test the images
+        run: assets/test.sh "ghcr.io/pulp/pulp:$VERSION"
+      - name: Docker login
+        env:
+          PULP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          DOCKER_BOT_USERNAME: ${{ secrets.DOCKER_BOT_USERNAME }}
+        run: echo "$PULP_GITHUB_TOKEN" | docker login -u "$DOCKER_BOT_USERNAME" --password-stdin ghcr.io
+      - name: Push ci image to dockerhub
+        run: |
+          docker push ghcr.io/pulp/pulp:$VERSION
+          if [ "$VERSION" = "latest" ]; then
+            docker push ghcr.io/pulp/pulp-ci-centos:latest
+            docker push ghcr.io/pulp/pulp-galaxy-ng:latest
+            # Let this be the last thing so it can indicate failure without breaking anything else
+            docker push ghcr.io/pulp/pulp:nightly
+          fi
+      - name: Display log on error
+        if: failure()
+        run: docker logs pulp
